### ISSUE TITLE
Highlights are overriding

### ISSUE THREAD

**Issue by snikoletopoulos** [AstroNvim/astroui#13]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 release

### Operating system/version

macOS 14.4

### Terminal/GUI

WezTerm

### Describe the bug

When enabling NVChad telescope theme from AstroNvim Community and having custom unrelated highlights in astroui, the telescope highlights are overriden. Only when i remove my highlights is the theme applied

### Steps to Reproduce

1. Add NVChad telescope theme to community
2. Add custom highlights to init different from the telescope, ex. Cmp

### Expected behavior

The highlights should merge and both configs are applied

**Comment by mehalter** [comment]
Please provide some clearer steps for replication and some clear details on the actual behavior and expected behavior

**Comment by mehalter** [comment]
ah I see what you mean. I believe what you want to do is modify your configuration to play nicely with the telescope nvchad theme pack. Here is an example (assuming you have the `telescope-nvchad-theme` pack added:

```lua
return {
  "AstroNvim/astroui",
  opts = function(_, opts)
    local highlights_init = opts.highlights.init
    return require("astrocore").extend_tbl(opts, {
      highlights = {
        init = function()
          local highlights = type(highlights_init) == "function" and highlights_init() or highlights_init

          -- custom highlights building off of previously modified highlights
          highlights.Normal = { bg = "#ABCDEF" }

          return highlights
        end,
      },
    })
  end,
}
```
