### ISSUE TITLE
Heirline.nvim doesn't play with QuickList and LocList

### ISSUE THREAD

**Issue by wroyca** [AstroNvim/astroui#9]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev+2507-g3df1211eb

### Operating system/version

Linux fedora 6.7.7-200.fc39.x86_64

### Terminal/GUI

kitty 0.31.0

### Describe the bug

We're faced with some issues when we start using Quickfix and Loclist; these issues mostly include the ones I've found so far, and chance are that it's not inclusive so it's probably make sense to consider it as meta. 

- 1. Heirline draw it statuscol in Quickfix and LocList
- 2. Heirline will draw over the command line

Here's how it should look in practice:

![Screenshot from 2024-03-07 08-07-05](https://github.com/AstroNvim/astroui/assets/91024200/6639be22-f66a-44d6-847d-5a4eb50de8fa)

Here's how it currently look:

![image](https://github.com/AstroNvim/astroui/assets/91024200/a4499eaa-3d21-4760-a648-774edf3ff904)

One thing is that it almost looks as intended on the dashboard (minus the status column):

![image](https://github.com/AstroNvim/astroui/assets/91024200/c83cac12-95f7-4273-9126-8f4e741289f7)

### Steps to Reproduce

1. Use astrocommunity Coc
2. CocList ...

**Comment by mehalter** [comment]
This is unrelated to our heirline, it's actually working completely correctly. The extra column is coming from `foldcolumn="1"`, you want to set `foldcolumn="0"` for those filetypes. Also the command line being hidden is just a side effect of Coc not playing nicely with `cmdheight=0`, You probably want it to be `cmdheight=1` for coc to function correctly. Not sure if that should be reported to Neovim core or Coc.

**Comment by mehalter** [comment]
Here is a screenshot with `cmdheight=1` and `foldcolumn="0"`

![2024-03-07_09:22:34_screenshot](https://github.com/AstroNvim/astroui/assets/1591837/5b819bce-23b0-4cc9-9a3d-b16b7d88612d)

**Comment by mehalter** [comment]
also looking at it more it does look like it's more related to coc probably rather than neovim core to run down the issue
